#!/bin/bash

if ! command -v tuist &> /dev/null; then
  curl -Ls https://install.tuist.io | bash
  tuist update
fi

if ls ./*.xcworkspace 1> /dev/null 2>&1; then
  rm -rf *.xcworkspace
fi

if ls ./*.xcodeproj 1> /dev/null 2>&1; then
  rm -rf *.xcodeproj
fi

case $1 in
  "--edit")
    tuist edit
    ;;

  "--reset" | "--clean")
    ;;

  "--reset-deps" | "--clean-deps")
    tuist clean dependencies
    ;;

  *)
    tuist fetch
    tuist generate
    ;;
esac
